name: CI - closed pull-request

on:
  pull_request:
    types: [ closed ]

jobs:
  on-pull-request-merged-on-main:
    name: On pull-request merged on main
    runs-on: ubuntu-latest
    if: |
      github.event.pull_request.merged && github.event.pull_request.base.ref == 'main'
    permissions:
      pull-requests:
    steps:
      - name: test
        uses: 'thecanadianroot/open-pull-request-action@main'
        with:
          base: 'pre-production'
          head: ${{ github.event.pull_request.head.ref }}
          sha: ${{ github.event.pull_request.merge_commit_sha }}
          title: ${{ github.event.pull_request.title }}
          body: ${{ github.event.pull_request.body }}
          assignees: ${{ toJSON(github.event.pull_request.assignees.*.login) }}
          reviewers: ${{ toJSON(github.event.pull_request.reviewers.*.login) }}